apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "chart.fullname" . }}
spec:
  hosts:
  - "*"
  gateways:
  -  {{ include "chart.fullname" . }}
  http:
    route:
    - destination:
        host: {{ .host | quote }}
        port:
          number: {{ $svcPort }} 
