apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "chart.fullname" . }}
spec:
  hosts:
  - "*"
  gateways:
  -  {{ include "chart.fullname" . }}
    route:
    - destination:
        host: microprofile-poc.default
        port:
          number: 8080 
